### ISSUE TITLE
Failing to pull data for one server.

### ISSUE THREAD

**Issue by brookeburdick** [red5coder/Jamf-Protect-Batch-Delete#1]
I just used this handy tool to delete Macs from 6 other servers. This last server has API client with full admin, but when I try to click "fetch" nothing happens. I tried a wrong password just to check, and that gave an authentication error. I even created another client, no luck. Wondering if there is something I am missing for this instance, as it worked great for the other 6. There are 290 Macs in this instance. 

Pulled logging and this was the error: "Could not decode data from Protect."

<img width="1285" alt="Screenshot 2024-01-29 at 12 24 08 PM" src="https://github.com/red5coder/Jamf-Protect-Batch-Delete/assets/36173452/166fe34c-a946-460f-8814-66bab2033065">

Edit: I am able to get an authorization token and manually query with the credentials, so at least I know this API client is working for manually pulling info. 

Tried CSV, it says it deleted successfully, but nothing is actually deleted, same error: 
2024-01-29 12:51:57.856606-0800 0x77943    Info        0x12e3f8             97637  0    Jamf Protect Batch Delete: [co.uk.mallion.jamf-protect-batch-delete:protect] Fetching details from Protect.P

2024-01-29 12:51:57.982408-0800 0x77dbf    Error       0x12e3f8             97637  0    Jamf Protect Batch Delete: [co.uk.mallion.jamf-protect-batch-delete:protect] Could not decode data from Protect.

**Comment by brookeburdick** [comment]
Found the issue, there were some Macs with null-null that were causing the whole query to fail, once those Macs were removed it was successful! 
![Screenshot 2024-01-29 at 2 08 21 PM](https://github.com/red5coder/Jamf-Protect-Batch-Delete/assets/36173452/87685af2-0ce3-463e-b91d-40061ca4880c)

**Comment by red5coder** [comment]
Hi there. sorry about the delay.

Nice spot. Will see if I can work away around that if happens again. Must admit unusual. Thanks thou.
